Collect opengraph (#11)
* I #9 WIP: Covering cases up to book-isbn10

* Added LICENSE

* I #9 Full implementation of collectOpenGraph() and fully tested

* I #9 Precompiled XPATH queriesO

Using XPATH Context instead documentElement for queries.
Fixed failing tests.#10

* I #9: cleaned up implementation of collectOpengraph()

Better test coverage

* I #9  removed forgotten git markup duringconflict resolution

* I #9  Removed  doubled documentation sections

* polish HTML::Inspect::_init

* HTML::Inspect, move large collectOpenGraph() to the end

* HTML::Inspect \z$ expresses "end" twice

* fix disable Tasks

* HTML::Inspect minor

Co-authored-by: Mark Overmeer <mark@overmeer.net>

diff --git a/Pipeline/profile b/Pipeline/profile
--- a/Pipeline/profile
+++ b/Pipeline/profile
@@ -13,12 +13,12 @@ for TASK in $_T
 do
     if [ ${PIPELINE_TASK["$TASK"]:-on} = 'on' ]
     then PIPELINE_TASKS+=" $TASK"
-         unset PIPELINE_TASK["$TASK"]
     fi
+    unset PIPELINE_TASK["$TASK"]
 done
 
 if [ "${PIPELINE_TASK[*]}" != '' ]
-then echo "ERROR: unknown pipeline task: #${PIPELINE_TASK[@]}#" >&2
+then echo "ERROR: unknown pipeline task: #${!PIPELINE_TASK[@]}#" >&2
      exit 1
 fi
 
